version: '3.7'

services:
  db:
    container_name: cool-db
    image: "postgres:14.6"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
        - "5432:5432"

  redis:
    container_name: cool-redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
